FROM php:7-fpm
ENTRYPOINT [ "/docker-entrypoint" ]

ENV VUFIND_CACHE_DIR=/var/cache/vufind \
  VUFIND_APPLICATION_PATH=/usr/local/vufind \
  VUFIND_LOCAL_DIR=/usr/local/vufind/local \
  VUFIND_ENV=production \
  NODE_ENV=production \
  npm_config_registry=https://services.ub.uni-leipzig.de/nexus/repository/npm/

COPY assets/entrypoint-php /docker-entrypoint

RUN apt-get update \
  && apt-get install -y gnupg \
  && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
  && apt-get install -y  libicu57 libicu-dev libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev libxslt-dev libpq-dev nodejs git \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include --with-jpeg-dir=/usr/include \
  && docker-php-ext-install -j$(nproc) intl mysqli pdo_pgsql pdo_mysql pdo gd xsl intl soap \
  && pecl install mcrypt-1.0.1 \
  && docker-php-ext-enable mcrypt \
  && apt-get remove --purge -y libicu-dev libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev libxslt-dev libpq-dev gnupg \
  && npm install -g autoconfig eslint@"<3.0.0" \
  && rm /var/lib/apt/lists/* -rf \
  && pear install pear/Http_Request2 \
  && pear channel-discover pear.phing.info \
  && pear install phing/phing \
  && chmod a+x /docker-entrypoint

WORKDIR ${VUFIND_APPLICATION_PATH}

CMD [ "php-fpm" ]
