FROM services.ub.uni-leipzig.de:10443/node:8-alpine
ENTRYPOINT [ "/docker-entrypoint" ]

ENV VUFIND_APPLICATION_PATH=/usr/local/vufind \
 NODE_ENV=production \
 npm_config_registry=https://services.ub.uni-leipzig.de/nexus/repository/npm/

COPY assets/entrypoint-node-debug /docker-entrypoint

RUN apk add --no-cache python make g++ \
 && npm install -g autoconfig \
 && chmod a+x /docker-entrypoint

WORKDIR ${VUFIND_APPLICATION_PATH}