FROM httpd:alpine
ENTRYPOINT [ "/docker-entrypoint" ]
CMD ["httpd-foreground"]

ENV BASE_PATH=""

ADD assets/entrypoint-httpd /docker-entrypoint
RUN chmod a+x /docker-entrypoint

ADD assets/httpd.vufind1.conf /usr/local/apache2/conf/httpd.conf
