FROM php:7-fpm
VOLUME [ "/var/vache/vufind" ]
ENTRYPOINT [ "/docker-entrypoint" ]

ENV VUFIND_CACHE_DIR=/var/cache/vufind \
  VUFIND_APPLICATION_PATH=/usr/local/vufind \
  VUFIND_LOCAL_DIR=/usr/local/vufind/local \
  VUFIND_ENV=production

COPY assets/entrypoint-php /docker-entrypoint

RUN apt-get update \
  && apt-get install -y  libicu57 libicu-dev libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev libxslt-dev libpq-dev \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include --with-jpeg-dir=/usr/include \
  && docker-php-ext-install -j$(nproc) intl mysqli pdo_pgsql pdo_mysql pdo gd xsl >/dev/null \
  && pecl install mcrypt-1.0.1 >/dev/null \
  && docker-php-ext-enable mcrypt \
  && apt-get remove --purge -y libicu-dev libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev libxslt-dev libpq-dev \
  && chmod a+x /docker-entrypoint

CMD [ "php-fpm" ]
