#!/bin/bash

set -e

if [ "${VUFIND_SOLR}" == "local" ]; then
	if [ -e ${APP_HOME}/solr.sh ]; then
		SOLR_START_SCRIPT=${APP_HOME}'/solr.sh start'
	else
		SOLR_START_SCRIPT=${APP_HOME}'/vufind.sh run'
	fi;

	cat > /etc/supervisor/conf.d/solr.conf <<EOF
[program:solr]
priority = 20
directory = /tmp
command = ${SOLR_START_SCRIPT}
environment = VUFIND_HOME="${APP_HOME}",SOLR_ADDITIONAL_START_OPTIONS=-f
user = ${APP_USER}
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile = ${LOG_DIR}/supervisor/supervisord.log
EOF

fi
