#!/bin/bash

set -e

if [ "${VUFIND_SOLR}" == "local" ]; then
	if [ -e ${APP_HOME}/solr.sh ]; then
		SOLR_START_SCRIPT=${APP_HOME}'/solr.sh start -f -p 8080'
	else
		SOLR_START_SCRIPT=${APP_HOME}/vufind.sh run
	fi;

	cat > /etc/supervisor/conf.d/solr.conf <<EOF
[program:solr]
priority = 20
directory = /tmp
command = ${SOLR_START_SCRIPT}
environment = VUFIND_HOME="${APP_HOME}"
user = ${APP_USER}
autostart = true
autorestart = true
stdout_logfile = ${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile = ${LOG_DIR}/supervisor/%(program_name)s.log
EOF

fi
