#!/bin/bash

set -e
VUFIND_SOLR="${VUFIND_SOLR:-local}"

VUFIND_HTTPD_CONF="${APP_HOME}/${VUFIND_HTTPD_CONF:-local/httpd-vufind.conf}"
VUFIND_HTTPD_LINK="/etc/apache2/sites-enabled/00-httpd-vufind2.conf"

if [ ! -e "${VUFIND_HTTPD_CONF}" ];then
    su -l dev -c "php ${APP_HOME}/install.php --non-interactive"
    test -e "${VUFIND_HTTPD_LINK}" && rm "${VUFIND_HTTPD_LINK}";
fi;

# we have to remove all php_value options since we dont use php as apache2 module
sed -e 's/\(^\s*php_value\s\+.*\)/#\1/' -i ${VUFIND_HTTPD_CONF}

# we change vufinds default path to ${APP_HOME}'s path
sed -e 's!/usr/local/vufind2!'${APP_HOME}'!g' -i ${VUFIND_HTTPD_CONF}

# if there is no symbolic link for apache2 config create one
if [ ! -h "${VUFIND_HTTPD_LINK}" ]; then
    ln -s ${VUFIND_HTTPD_CONF} ${VUFIND_HTTPD_LINK}
fi;

# if there is a package.json, we call npm install to install all required local components
if [ -e ${APP_HOME}/package.json ]; then
    echo "Installing locally required npm packages ..."
    su -l dev -c "cd ${APP_HOME};npm install"
fi;

# if there is a gruntfile in the sources, we want to start grunt-watch to compile all necessities
if [ -e ${APP_HOME}/[gG]runtfile.js ]; then
    echo "Setting up Vufind2 grunt-watcher for autostart ..."
    sed -e 's/^\(^\s*autostart\s*=\s*\).*$/\1true/' -i /etc/supervisor/conf.d/grunt-watch.conf
fi;

if [ "${VUFIND_SOLR}" == "local" ]; then
    echo "Setting up Vufind2 Solr for autostart ..."
    sed -e 's/^\(^\s*autostart\s*=\s*\).*$/\1true/' -i /etc/supervisor/conf.d/solr.conf
fi;

VUFIND_LOCAL_DIR=`grep -E '^\s*SetEnv\s+VUFIND_LOCAL_DIR' "${VUFIND_HTTPD_LINK}" | perl -pe 's!^\s*SetEnv\s+VUFIND_LOCAL_DIR\s+([^\s]+)\s*$!$1!'`
sed -e 's!^\(export VUFIND_LOCAL_DIR="\)[^\"]\+"!\1'${VUFIND_LOCAL_DIR}'"!' -i /home/dev/.profile
