#!/bin/bash

set -e

VUFIND_HTTPD_CONF="${APP_HOME}/${VUFIND_HTTPD_CONF}"
VUFIND_HTTPD_LINK="/etc/apache2/sites-enabled/10-httpd-vufind2.conf"

if [ ! -e "${VUFIND_HTTPD_CONF}" ];then
    su -l ${APP_USER} -c "php ${APP_HOME}/install.php --non-interactive"
    test -e "${VUFIND_HTTPD_LINK}" && rm "${VUFIND_HTTPD_LINK}";
fi;

# if there is no symbolic link for apache2 config create one
if [ ! -h "${VUFIND_HTTPD_LINK}" ]; then
    ln -s ${VUFIND_HTTPD_CONF} ${VUFIND_HTTPD_LINK}
fi;

# we change vufinds default path to ${APP_HOME}'s path
sed -e 's!/usr/local/vufind2!'${APP_HOME}'!g' -i ${VUFIND_HTTPD_CONF}

# we have to remove all php_value options since we dont use php as apache2 module
sed -e 's/\(^\s*php_value\s\+.*\)/#\1/' -i ${VUFIND_HTTPD_CONF}

if ! grep -q VUFIND_HOME /home/${APP_USER}/.profile; then
    cat >> /home/${APP_USER}/.profile <<EOF
export VUFIND_HOME=${APP_HOME}
export VUFIND_LOCAL_DIR="${APP_HOME}/local"
EOF
fi

VUFIND_LOCAL_DIR=`grep -E '^\s*SetEnv\s+VUFIND_LOCAL_DIR' "${VUFIND_HTTPD_LINK}" | perl -pe 's!^\s*SetEnv\s+VUFIND_LOCAL_DIR\s+([^\s]+)\s*$!$1!'`
sed -e 's!^\(export VUFIND_LOCAL_DIR="\)[^\"]\+"!\1'${VUFIND_LOCAL_DIR}'"!' -i /home/${APP_USER}/.profile
