#!/bin/bash

set -e

VUFIND2_HTTPD_CONF="${VUFIND_HOME}/local/httpd-vufind.conf"
VUFIND2_HTTPD_LINK="/etc/apache2/sites-enabled/httpd-vufind2.conf"

if [ ! -e "${VUFIND2_HTTPD_CONF}" ];then
    _setupVufind --non-interactive
    # we have to remove all php_value options since we dont use php as apache2 module
    sed -e 's/\(^\s*php_value\s\+.*\)/#\1/' -i ${VUFIND2_HTTPD_CONF}
fi;

if [ ! -h "${VUFIND2_HTTPD_LINK}" ]; then
    ln -s /usr/local/vufind2/local/httpd-vufind.conf ${VUFIND2_HTTPD_LINK}
fi;