#!/bin/bash
# creates default mysql database if not exists

# fix permissions and ownership of /var/lib/mysql
mkdir -p -m 700 /var/lib/mysql
chown -R mysql:mysql /var/lib/mysql

# fix permissions and ownership of /run/mysqld
mkdir -p -m 0755 /run/mysqld
chown -R mysql:root /run/mysqld

# initialize MySQL data directory
if [ ! -d /var/lib/mysql/mysql ]; then
    echo "Installing database..."
    cp /usr/share/doc/mysql-server-5.6/examples/my-default.cnf /usr/share/mysql/
    mysql_install_db --user=mysql >/dev/null 2>&1

    # start mysql server
    echo "Starting MySQL server..."
    /usr/bin/mysqld_safe >/dev/null 2>&1 &

    # wait for mysql server to start (max 30 seconds)
    timeout=30
    while ! /usr/bin/mysqladmin -u root status >/dev/null 2>&1
    do
        timeout=$(($timeout - 1))
        if [ $timeout -eq 0 ]; then
            echo "Could not connect to mysql server. Aborting..."
            exit 1
        fi
        echo "Waiting for database server to accept connections..."
        sleep 1
    done

    ## create a localhost only, debian-sys-maint user
    ## the debian-sys-maint is used while creating users and database
    ## as well as to shut down or starting up the mysql server via mysqladmin
    echo "Creating debian-sys-maint user..."
    mysql -uroot -e "GRANT ALL PRIVILEGES on *.* TO 'debian-sys-maint'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION;"

    echo "Setting root user password"
    /usr/bin/mysqladmin -u root password "${DB_PASS}"

    /usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf shutdown
fi