#!/bin/sh
set -e

sed -e 's!location \(/themes\|/cache\|\)/\s!location '${BASE_PATH}'\1/ !' -i /etc/nginx/conf.d/default.conf
sed -e 's!\(try_files $uri $uri/ \)\(/index.php\)!\1'${BASE_PATH}'\2!' -i /etc/nginx/conf.d/default.conf

exec "$@"