#!/bin/bash
set -e

if [ ! -d "${VUFIND_APPLICATION_PATH}" ];then
	echo "the application folder \"${VUFIND_APPLICATION_PATH}\" was not found. make shure to attach a sufficiently set up vufind container"
	exit 1;
fi;

APP_UID=`stat -c %u ${VUFIND_APPLICATION_PATH}`
APP_GID=`stat -c %g ${VUFIND_APPLICATION_PATH}`
APP_USER_HOME=`grep -e '^www-data' /etc/passwd | awk -F":" '{ print $6; }'`

# we do not allow root to be the app user
if [ "$APP_UID" == "0" -o "$APP_GID" == "0" ]; then
	echo "Setting app user to UID:1000 and GID:1000 ..."
	APP_UID="1000"
	APP_GID="1000"
	chown ${APP_UID}:${APP_GID} ${VUFIND_APPLICATION_PATH} -R
fi;

sed -e "s!^\(www-data:x\):[0-9]\+:[0-9]\+:\(.*\)\$!\1:${APP_UID}:${APP_GID}:\2!" -i /etc/passwd
sed -e "s!^\(www-data:x\):[0-9]\+:\(.*\)\$!\1:${APP_GID}:\2!" -i /etc/group

mkdir -p ${VUFIND_CACHE_DIR}

chown www-data:www-data ${VUFIND_APPLICATION_PATH} ${VUFIND_CACHE_DIR} ~www-data -R

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" -o "$1" == "php-fpm" ]; then
	exec docker-php-entrypoint "$@"
else
	exec su -s /bin/bash www-data -c "docker-php-entrypoint $*"
fi